# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HP_E4406_Wideband_Window.ui'
#
# Created: Fri Apr 18 09:00:15 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(750, 520)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Z_Icon.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Freq_Start_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.Freq_Start_lineEdit.setGeometry(QtCore.QRect(90, 85, 101, 27))
        self.Freq_Start_lineEdit.setObjectName(_fromUtf8("Freq_Start_lineEdit"))
        self.Freq_Stop_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.Freq_Stop_lineEdit.setGeometry(QtCore.QRect(90, 125, 101, 27))
        self.Freq_Stop_lineEdit.setObjectName(_fromUtf8("Freq_Stop_lineEdit"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(70, 425, 166, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.single_graph_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.single_graph_checkBox.setGeometry(QtCore.QRect(70, 215, 21, 41))
        self.single_graph_checkBox.setText(_fromUtf8(""))
        self.single_graph_checkBox.setChecked(True)
        self.single_graph_checkBox.setObjectName(_fromUtf8("single_graph_checkBox"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 215, 141, 41))
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(75, 320, 121, 19))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ip1_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ip1_lineEdit.setGeometry(QtCore.QRect(25, 345, 41, 27))
        self.ip1_lineEdit.setObjectName(_fromUtf8("ip1_lineEdit"))
        self.ip2_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ip2_lineEdit.setGeometry(QtCore.QRect(75, 345, 41, 27))
        self.ip2_lineEdit.setObjectName(_fromUtf8("ip2_lineEdit"))
        self.ip3_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ip3_lineEdit.setGeometry(QtCore.QRect(125, 345, 41, 27))
        self.ip3_lineEdit.setObjectName(_fromUtf8("ip3_lineEdit"))
        self.ip4_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ip4_lineEdit.setGeometry(QtCore.QRect(175, 345, 41, 27))
        self.ip4_lineEdit.setObjectName(_fromUtf8("ip4_lineEdit"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 345, 16, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 345, 16, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 345, 16, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 90, 41, 19))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 130, 41, 19))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.save_data_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.save_data_checkBox.setGeometry(QtCore.QRect(70, 265, 21, 41))
        self.save_data_checkBox.setText(_fromUtf8(""))
        self.save_data_checkBox.setChecked(True)
        self.save_data_checkBox.setObjectName(_fromUtf8("save_data_checkBox"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 265, 126, 41))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ip_port_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ip_port_lineEdit.setGeometry(QtCore.QRect(230, 345, 56, 27))
        self.ip_port_lineEdit.setObjectName(_fromUtf8("ip_port_lineEdit"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 320, 46, 19))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 80, 41, 41))
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(50, 120, 41, 41))
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 50, 131, 41))
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.output_plot_label = QtGui.QLabel(self.centralwidget)
        self.output_plot_label.setEnabled(True)
        self.output_plot_label.setGeometry(QtCore.QRect(320, 65, 400, 400))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_plot_label.sizePolicy().hasHeightForWidth())
        self.output_plot_label.setSizePolicy(sizePolicy)
        self.output_plot_label.setMinimumSize(QtCore.QSize(400, 400))
        self.output_plot_label.setMaximumSize(QtCore.QSize(400, 400))
        self.output_plot_label.setAutoFillBackground(False)
        self.output_plot_label.setFrameShape(QtGui.QFrame.Box)
        self.output_plot_label.setFrameShadow(QtGui.QFrame.Raised)
        self.output_plot_label.setLineWidth(1)
        self.output_plot_label.setMidLineWidth(1)
        self.output_plot_label.setText(_fromUtf8(""))
        self.output_plot_label.setPixmap(QtGui.QPixmap(_fromUtf8("spectrum_plot_empty.png")))
        self.output_plot_label.setScaledContents(True)
        self.output_plot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.output_plot_label.setWordWrap(True)
        self.output_plot_label.setOpenExternalLinks(True)
        self.output_plot_label.setObjectName(_fromUtf8("output_plot_label"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(205, 0, 446, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(240, 25, 256, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(90, 165, 181, 41))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.capture_average_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.capture_average_checkBox.setGeometry(QtCore.QRect(70, 165, 21, 41))
        self.capture_average_checkBox.setText(_fromUtf8(""))
        self.capture_average_checkBox.setChecked(True)
        self.capture_average_checkBox.setObjectName(_fromUtf8("capture_average_checkBox"))
        self.file_result_label = QtGui.QLabel(self.centralwidget)
        self.file_result_label.setGeometry(QtCore.QRect(320, 470, 401, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.file_result_label.setFont(font)
        self.file_result_label.setText(_fromUtf8(""))
        self.file_result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.file_result_label.setWordWrap(False)
        self.file_result_label.setObjectName(_fromUtf8("file_result_label"))
        self.execute_pushButton = QtGui.QPushButton(self.centralwidget)
        self.execute_pushButton.setGeometry(QtCore.QRect(100, 390, 102, 27))
        self.execute_pushButton.setObjectName(_fromUtf8("execute_pushButton"))
        self.stop_pushButton = QtGui.QPushButton(self.centralwidget)
        self.stop_pushButton.setGeometry(QtCore.QRect(100, 455, 102, 27))
        self.stop_pushButton.setObjectName(_fromUtf8("stop_pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "E4406A Span Concatenator", None, QtGui.QApplication.UnicodeUTF8))
        self.Freq_Start_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.Freq_Stop_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Fit all spans on single 10x10 span", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "VSA I.P. Address", None, QtGui.QApplication.UnicodeUTF8))
        self.ip1_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "192", None, QtGui.QApplication.UnicodeUTF8))
        self.ip2_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "168", None, QtGui.QApplication.UnicodeUTF8))
        self.ip3_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ip4_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Save data to file", None, QtGui.QApplication.UnicodeUTF8))
        self.ip_port_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "5025", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Frequency Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#00007f;\">HP/Agilent E4406A Span Concatenator   </span><span style=\" font-size:10pt; font-style:italic; color:#00007f;\">v1</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "By Bertrand Zauhar, VE2ZAZ.   ve2zaz.net", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Capture Average Curve (averaging must be on)", None, QtGui.QApplication.UnicodeUTF8))
        self.execute_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))

